server:
  port: 8889
spring:
  application:
    name: backend-admin
  profiles:
    active: @profiles.active@
  jpa:
    database: MySQL
    showSql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  data:
    rest:
      defaultPageSize: 10   # 分页大小 默认为 20
      maxPageSize: 100
      pageParamName: pageNumber # 当前页参数名 默认为 page
      limitParamName: pageSize # 当前页参数名 默认为 size
      sortParamName: orderBy
logging:
  config: classpath:config/logback-spring.xml




